
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      # - discovery.type=single-node            # <-- 1-box setup      
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ES_JAVA_OPTS=-Xms8g -Xmx8g            # <-- heap for 16 GB host (dedicated)
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnetnew

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.2
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - esnetnew

  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:8.17.3
  #   container_name: filebeat
  #   user: root
  #   environment:
  #     - "logging.level=debug"
  #   volumes:
  #     - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./filebeatconfig.yaml:/usr/share/filebeat/filebeat.yml:ro
  #   depends_on:
  #     - es01
  #     - es02
  #   networks:
  #     - esnetnew

  kib01:
    image: docker.elastic.co/kibana/kibana:9.1.2
    container_name: kib01
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
    ports:
      - 5601:5601
    networks:
      - esnetnew

  # logger:
  #   build:
  #     dockerfile: ./Dockerfile
  #   container_name: log-generator
  #   networks:
  #     - esnetnew


volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local

networks:
  esnetnew:
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: 172.18.0.0/16
    