filebeat.inputs:
- type: container
  paths:
    - /var/lib/docker/containers/*/*.log
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: log
  # multiline.pattern: '^{'
  # multiline.negate: true
  # multiline.match: after
  containers:
    ids:
      - "*log-generator*"

output.elasticsearch:
  hosts: ["http://es01:9200"]
  index: "logsdemo"
  # username: "elastic"  # Optional: if authentication is required
  # password: "changeme"  # Optional: if authentication is required

setup.template.name: "logsdemo"
setup.template.pattern: "logsdemo-*"
setup.ilm.enabled: false

logging.level: debug